osx: fixed to compile (x86_64 arch)
fixed size_t/uint64_t mismatch, string literal concatenation and
missing forward declarations for internal functions;
avoid using incompatible compiler and linker options for OSX;
improved build scripts (requires brew installed);

diff --git a/cvsnt/build-macosx b/cvsnt/build-macosx
--- a/cvsnt/build-macosx
+++ b/cvsnt/build-macosx
@@ -1,6 +1,36 @@
-cd cvsnt-2.5.05.3744/osx
-sudo mkdir /usr/local/include
-sudo tar -xzf usr_local_include_pcre.tar.gz -C /usr/local/include
+if ! command -v brew &> /dev/null
+then
+    echo "brew not found but required"
+    echo "install brew with:"
+    echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)\""
+    exit 1
+
+    # brew may be later uninstalled with
+    #   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
+fi
+
+brew install autoconf
+brew install automake
+brew install pkg-config
+brew install libtool
+brew install pcre
+
+cd cvsnt-2.5.05.3744
+autoreconf -i --force
+if [ $? != 0 ]; then
+  echo "ERROR: autoconf failed!"
+  exit 2
+fi
+
+cd zstd
+CFLAGS="-arch x86_64" LDFLAGS="-arch x86_64" make install
+cd ..
+
+cd osx
 ./build-mac
+if [ $? != 0 ]; then
+  echo "ERROR: build-mac failed!"
+  exit 3
+fi
 cd ../..
-cp cvsnt-2.5.05.3744/osx/cvsnt-2.*.tar.gz .
+cp cvsnt-2.5.05.3744/osx/cvsnt-*.tar.gz .
diff --git a/cvsnt/cvsnt-2.5.05.3744/osx/build-mac b/cvsnt/cvsnt-2.5.05.3744/osx/build-mac
--- a/cvsnt/cvsnt-2.5.05.3744/osx/build-mac
+++ b/cvsnt/cvsnt-2.5.05.3744/osx/build-mac
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -x
 set -v
-BuildPackage=0
+BuildPackage=1
 BuildODBC=0
 PackageName="g-cvsnt"
 
@@ -30,10 +30,23 @@ rm -rf $Distribution_Dir
 
 SAVEDIR=`pwd`
 cd $SourceRoot/..
+automake
+if [ $? != 0 ]; then
+  echo "ERROR: automake failed!"
+  exit 2
+fi
 make clean
-./configure --prefix=/usr/local --with-config-dir=/private/etc/cvsnt CC="clang" CPP="clang -E" CXX="clang++" LDFLAGS="-m64" CPPFLAGS="-m64" --with-internal-zlib CXXFLAGS="-arch x86_64 -D__DARWIN_OS__=`uname -r | sed s/'\.[0-9,\.]*$'//`" CFLAGS="-D__DARWIN_OS__=`uname -r | sed s/'\.[0-9,\.]*$'//`" --disable-odbc --disable-ltdl --disable-postgres --disable-server --disable-mysql --disable-sspi --disable-sqlite --disable-odbc --enable-64bit
+./configure --with-config-dir=/private/etc/cvsnt CC="clang -arch x86_64 -msse4.1" CPP="clang -arch x86_64 -msse4.1 -E" CXX="clang++ -arch x86_64 -msse4.1 -std=gnu++14" --with-internal-zlib --disable-ltdl --disable-odbc --disable-postgres --disable-server --disable-mysql --disable-sspi --disable-sqlite --disable-odbc --enable-64bit
+if [ $? != 0 ]; then
+  echo "ERROR: configure failed!"
+  exit 1
+fi
 rm -rf $InstallerRoot/* 
 make -j8 install DESTDIR=$InstallerRoot
+if [ $? != 0 ]; then
+  echo "ERROR: make failed!"
+  exit 3
+fi
 # make install DESTDIR=$InstallerRoot
 cd $SAVEDIR
 
